{application,schejex,
             [{registered,[]},
              {description,"schejex"},
              {vsn,"0.1.0"},
              {modules,['Elixir.Consumer','Elixir.ConsumerManager',
                        'Elixir.Request','Elixir.Scheduler','Elixir.Schejex',
                        'Elixir.TickServer','Elixir.User']},
              {applications,[kernel,stdlib,elixir,logger]},
              {mod,{'Elixir.Schejex',[]}}]}.